### ISSUE TITLE
100 real steps for Allo Relay Attenuator

### ISSUE THREAD

**Issue by AlexValery13** [allocom/RelayAttenuator#1]
Hi!

I use Relay Attenuator, thanks!

I would like to add one more relay, and get "100 real steps". I understand how to change the hardware. I need to have "100 real steps" on i2c without interpolation. Yuo can help me in this?

**Comment by allocom** [comment]
Hi,   What kind of help are you expecting from me?

**Comment by AlexValery13** [comment]
I suppose that there are some constants. If you tell me about them, then I will be able to advance longer. I can use WinSCP.

**Comment by allocom** [comment]
You have to be more specific on what you want to know? what constants are you talking? Is it related to hardware or software????

**Comment by AlexValery13** [comment]
Sorry for my English.
I have no questions about the scheme. I know how to connect another relay. The i2C to Parallel-Port Expander has 8 channels. You use 6 channels to control the volume switch. And one more relay is used for mute. One channel remains free. I want to install in this channel one more relay and resistance. I know how to do it.
My question is about the software. You pass on i2c 64 binary code combinations to control 6 relays. To control the 7 relays must transmit 128 binary code combinations over i2c. Really, I want to use only 100 combinations at the top. The adjustment will be 100db. I hope that the current restriction in 64 combinations is established by constants.

**Comment by allocom** [comment]
Yes, it is restricted to 64 steps, you can modify the upper limit (0x3F) to your value in ra_mute, ra_vol_inc, ra_vol_dec & ra_vol_set functions. Note that relay 7 is used for mute, you adding another relay should be right after the 6th relay. 
Please provide your email ID, we can communicate. I don't want to continue here as this is for software Issues.

**Comment by AlexValery13** [comment]
Yes, you correctly understood my question! Many thanks! 
Where can I find these variables? In what folder are they located? 
About the relay, I understand everything. 
My e-mail is 
*************
and I'm waiting for a letter from you :)
